# spring boot 配置文件

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20000714@Lwh

  # 阿里云OSS配置
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    accessKeyId: *****
    accessKeySecret: *****
    bucketName: web-hngutg-test1

  # redis
  redis:
    host: localhost
    port: 6379
    password: *****
    database: 0